#!/usr/bin/env node
// Writes panel/src/ui/tokens.css from brand/tokens.json (plan 2026-10-05, task 9): the base palette, the brand font
// families with the brand fallback, and the leading, as CSS custom properties under :root. The panel itself draws
// in the system UI font (SB Sans is not shipped, spec 8.1), so the font tokens are for brand pieces, not for the
// panel's text. The extended palette stays out until a decision brings it in (tokens.json color.extended).
// The file is committed; tests/panel/ui/tokens-css.test.ts fails when it is stale.
//   node tools/panel/tokens-css.mjs [--check]
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
export const OUT = path.join(REPO, 'panel', 'src', 'ui', 'tokens.css');
const TOKENS = path.join(REPO, 'brand', 'tokens.json');

const HEADER = '/* Generated by tools/panel/tokens-css.mjs from brand/tokens.json; do not edit. */';
const HEX = /^#[0-9A-Fa-f]{6}$/;

// 'displayRegular' -> 'display': the family a token of tokens.type.fonts belongs to.
const familyKey = (tokenName) => /^[a-z]+/.exec(tokenName)?.[0] ?? tokenName;

// 'SBSansDisplay-Semibold' -> 'SB Sans Display'.
export function familyName(postScriptName) {
  return String(postScriptName)
    .split('-')[0]
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2');
}

export function readTokens(file = TOKENS) {
  return JSON.parse(readFileSync(file, 'utf8'));
}

/** @param {any} [tokens] the parsed brand/tokens.json @returns {string} */
export function generate(tokens = readTokens()) {
  const base = tokens && tokens.color && tokens.color.base;
  if (!base || typeof base !== 'object') throw new Error('tokens.json has no color.base');
  const lines = [HEADER, ':root {', '  /* palette: color.base */'];
  for (const [name, c] of Object.entries(base)) {
    if (name.startsWith('_')) continue;
    if (!c || !HEX.test(c.hex)) throw new Error(`tokens.json color.base.${name}.hex is not a #RRGGBB colour: ${JSON.stringify(c && c.hex)}`);
    lines.push(`  --crbk-color-${name}: ${c.hex};`);
  }

  const type = (tokens && tokens.type) || {};
  const fallback = typeof type.fallback === 'string' && type.fallback ? type.fallback : null;
  const families = new Map();
  for (const [name, f] of Object.entries(type.fonts || {})) {
    if (name.startsWith('_') || !f || !f.postScriptName) continue;
    const key = familyKey(name);
    if (!families.has(key)) families.set(key, familyName(f.postScriptName));
  }
  if (families.size) {
    lines.push('', '  /* type: type.fonts families and type.fallback */');
    for (const [key, family] of families) {
      lines.push(`  --crbk-font-${key}: "${family}", ${fallback ? fallback + ', ' : ''}sans-serif;`);
    }
  }
  const leading = type.leading || {};
  const leads = Object.entries(leading).filter(([k, v]) => !k.startsWith('_') && typeof v === 'number');
  if (leads.length) {
    lines.push('', '  /* type: type.leading */');
    for (const [k, v] of leads) lines.push(`  --crbk-leading-${k}: ${v};`);
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

// The committed file with LF (core.autocrlf may check it out with CRLF), or null if it is missing.
export function readGenerated(file = OUT) {
  try {
    return readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  } catch {
    return null;
  }
}

// Writes the file when it is missing or differs from what the generator gives; -> true when it wrote.
export function refresh(file = OUT, css = generate()) {
  if (readGenerated(file) === css) return false;
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, css, 'utf8');
  return true;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const css = generate();
  const rel = path.relative(REPO, OUT).replace(/\\/g, '/');
  if (process.argv.includes('--check')) {
    const fresh = readGenerated() === css;
    console.log(fresh ? `fresh ${rel}` : `STALE ${rel}: run node tools/panel/tokens-css.mjs`);
    if (!fresh) process.exitCode = 1;
  } else {
    console.log(`${refresh(OUT, css) ? 'wrote' : 'unchanged'} ${rel}`);
  }
}
