import { describe, it, expect } from 'vitest';
import tokens from '../../../brand/tokens.json';
import { generate, OUT, readGenerated } from '../../../tools/panel/tokens-css.mjs';

describe('tokens.css', () => {
  it('is the file the generator gives for brand/tokens.json (run: node tools/panel/tokens-css.mjs)', () => {
    expect(OUT.replace(/\\/g, '/')).toMatch(/panel\/src\/ui\/tokens\.css$/);
    expect(readGenerated()).toBe(generate());
  });

  it('has the base palette of the brand book as custom properties', () => {
    const css = generate();
    expect(css).toContain('--crbk-color-green: #26D07C;');
    for (const [name, c] of Object.entries(tokens.color.base)) {
      expect(css).toContain(`--crbk-color-${name}: ${c.hex};`);
    }
  });

  it('leaves out the extended palette: it is not for templates or the panel without a decision', () => {
    const css = generate();
    for (const name of Object.keys(tokens.color.extended).filter((k) => !k.startsWith('_'))) {
      expect(css).not.toContain(`--crbk-color-${name}`);
    }
  });

  it('names the brand font families with the fallback of the brand', () => {
    const css = generate();
    expect(css).toContain('--crbk-font-display: "SB Sans Display", Verdana, sans-serif;');
    expect(css).toContain('--crbk-font-text: "SB Sans Text", Verdana, sans-serif;');
    expect(tokens.type.fallback).toBe('Verdana');
  });

  it('carries the leading of the brand book', () => {
    const css = generate();
    expect(css).toContain('--crbk-leading-normal: 1.2;');
    expect(css).toContain('--crbk-leading-dense: 1;');
  });

  it('is plain ASCII with LF endings, in one :root block, and says it is generated', () => {
    const css = generate();
    expect(css).toMatch(/^\/\* Generated by tools\/panel\/tokens-css\.mjs/);
    // eslint-disable-next-line no-control-regex
    expect(/[^\x00-\x7f]/.test(css)).toBe(false);
    expect(css).not.toContain('\r');
    expect(css.match(/:root \{/g)).toHaveLength(1);
    expect(css.endsWith('}\n')).toBe(true);
  });

  it('is deterministic', () => {
    expect(generate()).toBe(generate());
  });

  it('refuses tokens without a palette or with a colour that is not one', () => {
    expect(() => generate({} as never)).toThrow(/color\.base/);
    expect(() => generate({ color: { base: { green: { hex: 'green' } } }, type: { fonts: {}, fallback: 'Verdana' } } as never)).toThrow(/green/);
  });
});
